---
submitty_install_submitty_url: localhost
submitty_install_submitty_email: submitty@localhost
submitty_install_submitty_ip: 127.0.0.1
submitty_install_ssl_cert_file: /etc/ssl/certs/submitty.pem
submitty_install_ssl_key_file: /etc/ssl/private/submitty.key
submitty_install_submitty_version: main
submitty_install_github_url: https://github.com/Submitty/Submitty.git
submitty_install_ssl_enabled: false
submitty_install_config_location: /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/data/configs/
