---
submitty_install_submitty_version: main
submitty_install_github_url: https://github.com/Submitty/Submitty.git
submitty_install_db_host: localhost
submitty_install_db_port: 5432
submitty_install_submitty_dbuser: submitty_dbuser
submitty_install_submitty_dbuser_password: submitty_password
submitty_install_submitty_course_dbuser: submitty_course_dbuser
submitty_install_submitty_course_dbuser_password: submitty_password
submitty_install_timezone: America/New_York
submitty_install_language: en_US
submitty_install_submitty_url: localhost
submitty_install_vcs_url: git.localhost
submitty_install_institution_name: Example University
submitty_install_sysadmin_email: sysadmin@localhost
submitty_install_submitty_email: submitty@localhost
submitty_install_institution_url: localhost
submitty_install_authentication_method: 1
submitty_install_email_enabled: y
submitty_install_ssl_enabled: false
submitty_install_admin_email: admin@localhost
submitty_install_submitty_ip: 127.0.0.1
submitty_install_admin_password: admin_password
submitty_install_noreply_email: noreply_email@localhost
submitty_install_smtp_server: mail.localhost
submitty_install_smtp_port: 25
