---
submitty_install_db_host: localhost
submitty_install_db_port: 5432
submitty_install_submitty_dbuser: submitty_dbuser
submitty_install_submitty_dbuser_password: Do Quick Password Labratory
submitty_install_submitty_course_dbuser: submitty_course_dbuser
submitty_install_submitty_course_dbuser_password: Course Quick Labratory User
submitty_install_timezone: America/Los_Angeles
submitty_install_language: en_US
submitty_install_course_materials_file_upload_limit_mb: 100
submitty_install_submitty_url: submitty.cs.wallawalla.edu
submitty_install_vcs_url: git@gitlab.cs.wallawalla.edu
submitty_install_institution_name: Walla Walla University
submitty_install_institution_url: cs.wallawalla.edu
submitty_install_sysadmin_email: sysadmin@localhost
submitty_install_submitty_email: submitty@localhost
submitty_install_authentication_method: 1
submitty_install_self_account_creation: n
submitty_install_admin_username: admin
submitty_install_email_enabled: n
submitty_install_admin_email: admin@localhost
submitty_install_submitty_ip: 127.0.0.1
submitty_install_admin_password: DO PASSWORD NOT USE
submitty_install_noreply_email: noreply_email@localhost
submitty_install_smtp_server: mail.localhost
submitty_install_smtp_port: 25
submitty_install_ssl_cert_file: /usr/local/share/ca-certificates/submitty-vm.crt
submitty_install_ssl_key_file: /etc/ssl/private/submitty-vm.key
submitty_install_submitty_version: main
submitty_install_github_url: https://github.com/Submitty/Submitty.git