---
# Example playbook
# You can customize the variable to the app_submitty role by looking the default/main.yml list of variables in the role.

- name: Install Submitty
  hosts: submitty
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Submitty
      ansible.builtin.include_role:
        name: app_submitty
      vars:
      # customize your submitty install by adding variables here
      # these variables override the default variables in the role
        submitty_version: v24.02.00
