---
# Submitty Course Creation Ansible script.
# Assumes that local user accounts for instructor and TA already exist.

- name: Create new groups for "{{ course }}" course.
  ansible.builtin.group:
    name: "{{ submitty_course_creation_groups }}"
    state: present
  loop:
    - "{{ course }}"
    - "{{ course }}_tas_www"
    - "{{ course }}_archive"
  loop_control:
    loop_var: submitty_course_creation_groups

- name: Add instructors to the course groups.
  ansible.builtin.user:
    name: "{{ instructor }}"
    groups: "{{ submitty_course_creation_groups }}"
    append: yes
  loop:
    - "{{ course }}"
    - "{{ course }}_tas_www"
    - "{{ course }}_archive"
  loop_control:
    loop_var: submitty_course_creation_groups

- name: Add special users to the "{{ course }}_tas_www" group.
  ansible.builtin.user:
    name: "{{ submitty_course_creation_users }}"
    groups: "{{ course }}_tas_www"
    append: yes
  loop:
    - submitty_php
    - submitty_daemon
    - submitty_cgi
  loop_control:
    loop_var: submitty_course_creation_users
  notify: Reload fpm

# TODO move to submitty install script
- name: Give course management permissions to "{{ instructor }}".
  ansible.builtin.user:
    name: "{{ submitty_course_creation_users }}"
    groups: "submitty_course_builders"
    append: yes
  loop:
    - submitty_php
    - submitty_daemon
    - submitty_cgi
    - "{{ instructor }}"
  loop_control:
    loop_var: submitty_course_creation_users
  notify: Reload fpm

- name: Create private directory/repository for "{{ course }}".
  ansible.builtin.file:
    path: "/var/local/submitty/private_course_repositories/{{ course }}"
    state: directory
    mode: '0770'

- name: Recursively add private directory ownership to "{{ instructor }}".
  ansible.builtin.file:
    path: "/var/local/submitty/private_course_repositories/{{ course }}"
    state: directory
    recurse: yes
    owner: "{{ instructor }}"
    group: "{{ course }}_tas_www"

- name: Recursively update permissions to private directory.
  ansible.builtin.file:
    path: "/var/local/submitty/private_course_repositories/{{ course }}"
    state: directory
    recurse: yes
    mode: g+s

# - name: Add dummy student account for "{{ instructor }}".
#   user:
#     name: "{{ instructor }}-stu"

- name: Add instructors to submitty users.
  ansible.builtin.expect:
    command: ./adduser.py "{{ instructor }}"
    chdir: /usr/local/submitty/sbin/
    echo: yes
    responses:
      (?m)^User givenname: "{{ firstname }}"
      (?m)^User preferred name: "{{ firstname }}"
      (?m)^User familyname: "{{ lastname }}"
      (?m)^User email: "{{ email }}"
      (?m)^User password: NotUsedWithLdap
  become: yes
  become_user: root

# Prepare the course directory and course database.
# Assumes top-level Submitty database exists.

- name: Run the create_course script to create a course.
  ansible.builtin.command:
    cmd: ./create_course.sh "{{ semester }}" "{{ course }}" "{{ instructor }}" "{{ course }}_tas_www"
    chdir: /usr/local/submitty/sbin/
  become: yes
  become_user: root
  notify: Reload fpm

- name: Add existing instructors to the course database.
  ansible.builtin.command:
    cmd: ./adduser_course.py "{{ instructor }}" "{{ semester }}" "{{ course }}"
    chdir: /usr/local/submitty/sbin/
  become: yes
  become_user: root
