name: 'Dependabot PR Title Fixer'
on:
  pull_request_target:
    # check when PR
    # * is created,
    # * title is edited, and
    # * new commits are added (to ensure failing title blocks merging)
    types: [ opened, reopened, edited, synchronize ]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: submitty/action-dependabot-title-fixer@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
