name: 'Label New Issues'

on:
  issues:
    types:
      - opened
jobs:
  notify_zulip:
    runs-on: ubuntu-latest
    steps:
      - name: Add Awaiting Triage Label
        if: github.event.label.name != 'Awaiting Triage'
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.SUBMITTY_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Submitty/Submitty/issues/${{ github.event.issue.number}}/labels \
          -d '{"labels":["Awaiting Triage"]}'