name: 'PR Title Check'
on:
  pull_request:
    # check when PR
    # * is created,
    # * title is edited, and
    # * new commits are added (to ensure failing title blocks merging)
    types: [ opened, reopened, edited, synchronize ]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          #
          # pull request titles format rules here:
          # https://submitty.org/developer/how_to_contribute#how-to-make-a-pull-request-pr-to-submitty
          #
          # [<TYPE>:<MODULE>] <SUBJECT>
          #
          regex: '^(\[SYSADMIN ACTION\])?((\[(Bugfix|Feature|Refactor|Testing|Documentation|VPAT|UI\/UX):(Submission|Autograding|Forum|Notifications|TAGrading|InstructorUI|RainbowGrades|System|Developer|API)\] .{2,40}$)|(\[DevDependency\]|\[Dependency\]) .{2,70})$'
