name: Move drafts to WIP and un-drafts to seeking reviewer
on:
  pull_request_target:
    types:
      - opened
      - converted_to_draft
      - ready_for_review

env:
  PR_ID: ${{ github.event.pull_request.number }}

jobs:
  sort-drafts:
    name: Move drafts to WIP and un-drafts to seeking reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Get PR project ID
        id: get-pr-id
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          PR_PROJECT_ID="$(gh project item-list -L 9999 --owner Submitty 1 --format json --jq "[.items[] | {id, labels, status, title: .content.title, repo: .content.repository, number: .content.number}] | .[] | select(.number == "$PR_ID").id")"
          echo "pr-project-id="${PR_PROJECT_ID:?}"" >> "$GITHUB_OUTPUT"

      - name: Checkout the repo
        uses: actions/checkout@v5

      - name: Move draft to Work in Progress
        if: ${{ (github.event.action == 'converted_to_draft') || ((github.event.action == 'opened') && (github.event.pull_request.draft == true)) }}
        env:
          PR_PROJECT_ID: ${{ steps.get-pr-id.outputs.pr-project-id }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          source .github/bin/board_automation_helper.sh
          gh project item-edit --project-id "$PROJECT_ID" --id "$PR_PROJECT_ID" --field-id "$STATUS_FIELD_ID" --single-select-option-id "$WIP_ID"
        shell: bash

      - name: Move ready for review to Seeking Reviewer
        if: ${{ github.event.action == 'ready_for_review' }}
        env:
          PR_PROJECT_ID: ${{ steps.get-pr-id.outputs.pr-project-id }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          source .github/bin/board_automation_helper.sh
          gh project item-edit --project-id "$PROJECT_ID" --id "$PR_PROJECT_ID" --field-id "$STATUS_FIELD_ID" --single-select-option-id "$SEEKING_REVIEWER_ID"
        shell: bash
